In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('laptopPrice.csv')

In [3]:
df = pd.read_csv(r'E:\Data science\Projects\Laptop\laptopPrice.csv')

In [4]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [5]:
df.info()  ####

<class 'pandas.DataFrame'>
RangeIndex: 823 entries, 0 to 822
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   brand              823 non-null    str
 1   processor_brand    823 non-null    str
 2   processor_name     823 non-null    str
 3   processor_gnrtn    823 non-null    str
 4   ram_gb             823 non-null    str
 5   ram_type           823 non-null    str
 6   ssd                823 non-null    str
 7   hdd                823 non-null    str
 8   os                 823 non-null    str
 9   os_bit             823 non-null    str
 10  graphic_card_gb    823 non-null    str
 11  weight             823 non-null    str
 12  warranty           823 non-null    str
 13  Touchscreen        823 non-null    str
 14  msoffice           823 non-null    str
 15  Price              823 non-null    int64
 16  rating             823 non-null    str
 17  Number of Ratings  823 non-null    int64
 18  Number of Reviews  823 non-null    int64
dtypes: int64(3), str(16)
memory usage: 122.3 KB

In [6]:
df.columns

Index(['brand', 'processor_brand', 'processor_name', 'processor_gnrtn',
       'ram_gb', 'ram_type', 'ssd', 'hdd', 'os', 'os_bit', 'graphic_card_gb',
       'weight', 'warranty', 'Touchscreen', 'msoffice', 'Price', 'rating',
       'Number of Ratings', 'Number of Reviews'],
      dtype='str')

In [7]:
df.processor_brand

0      Intel
1      Intel
2      Intel
3      Intel
4      Intel
       ...
818      AMD
819      AMD
820      AMD
821      AMD
822      AMD
Name: processor_brand, Length: 823, dtype: str

In [8]:
df.brand

0        ASUS
1      Lenovo
2      Lenovo
3        ASUS
4        ASUS
        ...
818      ASUS
819      ASUS
820      ASUS
821      ASUS
822    Lenovo
Name: brand, Length: 823, dtype: str

In [9]:
df.processor_name

0           Core i3
1           Core i3
2           Core i3
3           Core i5
4      Celeron Dual
           ...
818         Ryzen 9
819         Ryzen 9
820         Ryzen 9
821         Ryzen 9
822         Ryzen 5
Name: processor_name, Length: 823, dtype: str

In [10]:
df['brand']

0        ASUS
1      Lenovo
2      Lenovo
3        ASUS
4        ASUS
        ...
818      ASUS
819      ASUS
820      ASUS
821      ASUS
822    Lenovo
Name: brand, Length: 823, dtype: str

In [11]:
df['processor_brand']

0      Intel
1      Intel
2      Intel
3      Intel
4      Intel
       ...
818      AMD
819      AMD
820      AMD
821      AMD
822      AMD
Name: processor_brand, Length: 823, dtype: str

In [12]:
df['Number of Reviews']

0      0
1      5
2      1
3      0
4      0
      ..
818    0
819    0
820    0
821    0
822    4
Name: Number of Reviews, Length: 823, dtype: int64

In [13]:
df[['brand','processor_brand','Number of Reviews']]

      brand processor_brand  Number of Reviews
0      ASUS           Intel                  0
1    Lenovo           Intel                  5
2    Lenovo           Intel                  1
3      ASUS           Intel                  0
4      ASUS           Intel                  0
..      ...             ...                ...
818    ASUS             AMD                  0
819    ASUS             AMD                  0
820    ASUS             AMD                  0
821    ASUS             AMD                  0
822  Lenovo             AMD                  4

[823 rows x 3 columns]

In [14]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [15]:
df.head()

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0

In [16]:
df.head(10)

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
5,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,22990,3 stars,0,0
6,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,21990,3 stars,31,3
7,ASUS,Intel,Core i5,10th,8 GB,DDR4,0 GB,1024 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,58799,3 stars,0,0
8,Lenovo,Intel,Core i5,10th,4 GB,DDR4,0 GB,1024 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,49999,3 stars,0,0
9,acer,AMD,Ryzen 5,10th,4 GB,DDR4,0 GB,512 GB,Windows,32-bit,4 GB,Casual,No warranty,No,No,59990,4 stars,1946,240

In [17]:
df.tail()

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [18]:
df.tail(12)

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
811,ASUS,AMD,Ryzen 9,Not Available,4 GB,LPDDR4X,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,Yes,Yes,124990,4 stars,44,12
812,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,6 GB,Casual,No warranty,No,No,141990,4 stars,61,13
813,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,162990,3 stars,0,0
814,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,130500,3 stars,0,0
815,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,No warranty,No,No,116990,3 stars,0,0
816,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,32-bit,6 GB,Casual,No warranty,No,No,138990,3 stars,0,0
817,ASUS,AMD,Ryzen 9,Not Available,4 GB,LPDDR4X,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,Yes,Yes,234990,3 stars,0,0
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [19]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [20]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
818    False
819    False
820    False
821    False
822    False
Length: 823, dtype: bool

In [21]:
df.duplicated().sum()

np.int64(21)

In [22]:
df.drop_duplicates()

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [23]:
df.duplicated().sum()

np.int64(21)

In [24]:
df.drop_duplicates(inplace=True)  ####

In [25]:
df.duplicated().sum()

np.int64(0)

In [26]:
df.isnull()

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
819,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
820,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
821,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
822,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [27]:
df.isnull().sum()

brand                0
processor_brand      0
processor_name       0
processor_gnrtn      0
ram_gb               0
ram_type             0
ssd                  0
hdd                  0
os                   0
os_bit               0
graphic_card_gb      0
weight               0
warranty             0
Touchscreen          0
msoffice             0
Price                0
rating               0
Number of Ratings    0
Number of Reviews    0
dtype: int64

In [28]:
df.dropna()

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [29]:
df.dropna(inplace=True)

In [30]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [31]:
df['brand'].unique()

<StringArray>
['ASUS', 'Lenovo', 'acer', 'Avita', 'HP', 'DELL', 'MSI', 'APPLE']
Length: 8, dtype: str

In [32]:
df['brand'].nunique()

8

In [33]:
df['brand'].value_counts()

brand
ASUS      243
DELL      149
Lenovo    144
HP        136
acer       51
MSI        50
APPLE      23
Avita       6
Name: count, dtype: int64

In [34]:
df.drop(['weight', 'Touchscreen', 'graphic_card_gb'], axis=1, inplace=True)

In [35]:
char =df.select_dtypes(include='object')

C:\Users\Bhave\AppData\Local\Temp\ipykernel_1716\2101896211.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  char =df.select_dtypes(include='object')

In [36]:
char

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,warranty,msoffice,rating
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,No warranty,No,2 stars
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,No warranty,No,3 stars
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,No warranty,No,3 stars
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,No warranty,No,3 stars
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,No warranty,No,3 stars
...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,1 year,No,3 stars
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,1 year,No,3 stars
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,1 year,No,3 stars
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,1 year,No,3 stars
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,No warranty,No,4 stars

In [37]:
iint=df.select_dtypes(exclude='object')

In [38]:
iint

      Price  Number of Ratings  Number of Reviews
0     34649                  3                  0
1     38999                 65                  5
2     39999                  8                  1
3     69990                  0                  0
4     26990                  0                  0
..      ...                ...                ...
818  135990                  0                  0
819  144990                  0                  0
820  149990                  0                  0
821  142990                  0                  0
822   57490                 18                  4

[802 rows x 3 columns]

In [39]:
df.info()

<class 'pandas.DataFrame'>
Index: 802 entries, 0 to 822
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   brand              802 non-null    str
 1   processor_brand    802 non-null    str
 2   processor_name     802 non-null    str
 3   processor_gnrtn    802 non-null    str
 4   ram_gb             802 non-null    str
 5   ram_type           802 non-null    str
 6   ssd                802 non-null    str
 7   hdd                802 non-null    str
 8   os                 802 non-null    str
 9   os_bit             802 non-null    str
 10  warranty           802 non-null    str
 11  msoffice           802 non-null    str
 12  Price              802 non-null    int64
 13  rating             802 non-null    str
 14  Number of Ratings  802 non-null    int64
 15  Number of Reviews  802 non-null    int64
dtypes: int64(3), str(13)
memory usage: 106.5 KB

In [40]:
df[df['brand']=='Lenovo']

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,warranty,msoffice,Price,rating,Number of Ratings,Number of Reviews
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,No warranty,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,No warranty,No,39999,3 stars,8,1
8,Lenovo,Intel,Core i5,10th,4 GB,DDR4,0 GB,1024 GB,Windows,32-bit,No warranty,No,49999,3 stars,0,0
17,Lenovo,Intel,Celeron Dual,Not Available,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,No warranty,No,31999,4 stars,286,19
19,Lenovo,Intel,Celeron Dual,Not Available,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,No warranty,No,31799,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
771,Lenovo,AMD,Ryzen 7,Not Available,16 GB,DDR4,512 GB,0 GB,Windows,64-bit,1 year,No,73400,3 stars,0,0
784,Lenovo,AMD,Ryzen 7,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,1 year,Yes,130990,3 stars,0,0
787,Lenovo,AMD,Ryzen 7,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,1 year,Yes,77988,3 stars,0,0
795,Lenovo,AMD,Ryzen 7,Not Available,4 GB,DDR4,512 GB,1024 GB,Windows,32-bit,No warranty,No,80490,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,No warranty,No,57490,4 stars,18,4

In [41]:
df['processor_brand'].unique()

<StringArray>
['Intel', 'AMD', 'M1']
Length: 3, dtype: str

In [42]:
df[df['processor_brand']=='Intel']

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,warranty,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,No warranty,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,No warranty,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,No warranty,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,No warranty,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,No warranty,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
632,ASUS,Intel,Pentium Quad,Not Available,4 GB,LPDDR4,0 GB,1024 GB,Windows,64-bit,No warranty,No,27990,3 stars,0,0
633,ASUS,Intel,Pentium Quad,Not Available,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,1 year,No,25990,3 stars,4741,658
634,ASUS,Intel,Pentium Quad,Not Available,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,1 year,No,25990,3 stars,2736,350
635,ASUS,Intel,Pentium Quad,Not Available,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,No warranty,No,30780,3 stars,0,0
750,Lenovo,Intel,Ryzen 7,Not Available,4 GB,DDR4,512 GB,0 GB,Windows,32-bit,3 years,Yes,81490,3 stars,0,0

In [43]:
Laptop_lenovo_Intel=df[(df['brand']=='Lenovo') & (df['processor_brand']=='Intel')]

In [44]:
Laptop_lenovo_Intel

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,warranty,msoffice,Price,rating,Number of Ratings,Number of Reviews
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,No warranty,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,No warranty,No,39999,3 stars,8,1
8,Lenovo,Intel,Core i5,10th,4 GB,DDR4,0 GB,1024 GB,Windows,32-bit,No warranty,No,49999,3 stars,0,0
17,Lenovo,Intel,Celeron Dual,Not Available,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,No warranty,No,31999,4 stars,286,19
19,Lenovo,Intel,Celeron Dual,Not Available,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,No warranty,No,31799,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
567,Lenovo,Intel,Core i7,10th,16 GB,LPDDR4X,1024 GB,0 GB,Windows,64-bit,No warranty,No,119990,2 stars,2,1
571,Lenovo,Intel,Core i7,11th,16 GB,LPDDR4,1024 GB,0 GB,Windows,64-bit,1 year,Yes,85990,3 stars,7,2
574,Lenovo,Intel,Core i7,10th,16 GB,DDR4,1024 GB,0 GB,Windows,64-bit,1 year,Yes,234990,3 stars,0,0
593,Lenovo,Intel,Core i9,10th,16 GB,DDR4,1024 GB,0 GB,Windows,32-bit,No warranty,No,265998,3 stars,0,0
750,Lenovo,Intel,Ryzen 7,Not Available,4 GB,DDR4,512 GB,0 GB,Windows,32-bit,3 years,Yes,81490,3 stars,0,0

In [45]:
df.to_csv('cleaned_laptop.csv')

In [46]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,warranty,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,No warranty,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,No warranty,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,No warranty,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,No warranty,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,No warranty,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,1 year,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,1 year,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,1 year,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,1 year,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,No warranty,No,57490,4 stars,18,4

In [47]:
df['processor_brand'].unique()

<StringArray>
['Intel', 'AMD', 'M1']
Length: 3, dtype: str

In [48]:
processor_dict={
    'Intel':1, 'AMD':2, 'M1':3
}

In [49]:
df['processor_brand']=df['processor_brand'].map(processor_dict)

In [50]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,warranty,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,1,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,No warranty,No,34649,2 stars,3,0
1,Lenovo,1,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,No warranty,No,38999,3 stars,65,5
2,Lenovo,1,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,No warranty,No,39999,3 stars,8,1
3,ASUS,1,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,No warranty,No,69990,3 stars,0,0
4,ASUS,1,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,No warranty,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,2,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,1 year,No,135990,3 stars,0,0
819,ASUS,2,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,1 year,No,144990,3 stars,0,0
820,ASUS,2,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,1 year,No,149990,3 stars,0,0
821,ASUS,2,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,1 year,No,142990,3 stars,0,0
822,Lenovo,2,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,No warranty,No,57490,4 stars,18,4

In [51]:
df.info()

<class 'pandas.DataFrame'>
Index: 802 entries, 0 to 822
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   brand              802 non-null    str
 1   processor_brand    802 non-null    int64
 2   processor_name     802 non-null    str
 3   processor_gnrtn    802 non-null    str
 4   ram_gb             802 non-null    str
 5   ram_type           802 non-null    str
 6   ssd                802 non-null    str
 7   hdd                802 non-null    str
 8   os                 802 non-null    str
 9   os_bit             802 non-null    str
 10  warranty           802 non-null    str
 11  msoffice           802 non-null    str
 12  Price              802 non-null    int64
 13  rating             802 non-null    str
 14  Number of Ratings  802 non-null    int64
 15  Number of Reviews  802 non-null    int64
dtypes: int64(4), str(12)
memory usage: 106.5 KB

In [52]:
df['brand'].unique()

<StringArray>
['ASUS', 'Lenovo', 'acer', 'Avita', 'HP', 'DELL', 'MSI', 'APPLE']
Length: 8, dtype: str

In [53]:
brand_dict={
    'ASUS':1, 'Lenovo':2, 'acer':3, 'Avita':4, 'HP':5, 'DELL':6, 'MSI':7, 'APPLE':8
}

In [54]:
df.info()

<class 'pandas.DataFrame'>
Index: 802 entries, 0 to 822
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   brand              802 non-null    str
 1   processor_brand    802 non-null    int64
 2   processor_name     802 non-null    str
 3   processor_gnrtn    802 non-null    str
 4   ram_gb             802 non-null    str
 5   ram_type           802 non-null    str
 6   ssd                802 non-null    str
 7   hdd                802 non-null    str
 8   os                 802 non-null    str
 9   os_bit             802 non-null    str
 10  warranty           802 non-null    str
 11  msoffice           802 non-null    str
 12  Price              802 non-null    int64
 13  rating             802 non-null    str
 14  Number of Ratings  802 non-null    int64
 15  Number of Reviews  802 non-null    int64
dtypes: int64(4), str(12)
memory usage: 106.5 KB

In [55]:
brand_dict={
    'ASUS':1, 'Lenovo':2, 'acer':3, 'Avita':4, 'HP':5, 'DELL':6, 'MSI':7, 'APPLE':8
}

In [56]:
# df.rename(columns={'':'model'})

In [57]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,warranty,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,1,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,No warranty,No,34649,2 stars,3,0
1,Lenovo,1,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,No warranty,No,38999,3 stars,65,5
2,Lenovo,1,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,No warranty,No,39999,3 stars,8,1
3,ASUS,1,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,No warranty,No,69990,3 stars,0,0
4,ASUS,1,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,No warranty,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,2,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,1 year,No,135990,3 stars,0,0
819,ASUS,2,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,1 year,No,144990,3 stars,0,0
820,ASUS,2,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,1 year,No,149990,3 stars,0,0
821,ASUS,2,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,1 year,No,142990,3 stars,0,0
822,Lenovo,2,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,No warranty,No,57490,4 stars,18,4

In [58]:
df['brand_encoding']=df['brand'].map(brand_dict)

In [59]:
df.drop('brand_encoding', axis= 1, inplace=True)

In [60]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,warranty,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,1,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,No warranty,No,34649,2 stars,3,0
1,Lenovo,1,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,No warranty,No,38999,3 stars,65,5
2,Lenovo,1,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,No warranty,No,39999,3 stars,8,1
3,ASUS,1,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,No warranty,No,69990,3 stars,0,0
4,ASUS,1,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,No warranty,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,2,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,1 year,No,135990,3 stars,0,0
819,ASUS,2,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,1 year,No,144990,3 stars,0,0
820,ASUS,2,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,1 year,No,149990,3 stars,0,0
821,ASUS,2,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,1 year,No,142990,3 stars,0,0
822,Lenovo,2,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,No warranty,No,57490,4 stars,18,4

In [61]:
df['processor_name'].unique()

<StringArray>
[     'Core i3',      'Core i5', 'Celeron Dual',      'Ryzen 5',
      'Core i7',      'Core i9',           'M1', 'Pentium Quad',
      'Ryzen 3',      'Ryzen 7',      'Ryzen 9']
Length: 11, dtype: str

In [62]:
processor_name_dict={
      'Core i3':10,      'Core i5':20, 'Celeron Dual':30,'Ryzen 5':40,
      'Core i7':50,      'Core i9':60,           'M1':70, 'Pentium Quad':80,
      'Ryzen 3':90,      'Ryzen 7':100,      'Ryzen 9':111
}
df['processor_name']=df['processor_name'].map(processor_name_dict)

In [63]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,warranty,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,1,10,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,No warranty,No,34649,2 stars,3,0
1,Lenovo,1,10,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,No warranty,No,38999,3 stars,65,5
2,Lenovo,1,10,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,No warranty,No,39999,3 stars,8,1
3,ASUS,1,20,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,No warranty,No,69990,3 stars,0,0
4,ASUS,1,30,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,No warranty,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,2,111,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,1 year,No,135990,3 stars,0,0
819,ASUS,2,111,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,1 year,No,144990,3 stars,0,0
820,ASUS,2,111,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,1 year,No,149990,3 stars,0,0
821,ASUS,2,111,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,1 year,No,142990,3 stars,0,0
822,Lenovo,2,40,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,No warranty,No,57490,4 stars,18,4

In [64]:
df['processor_gnrtn'].unique()

<StringArray>
['10th', 'Not Available', '11th', '7th', '8th', '9th', '4th', '12th']
Length: 8, dtype: str

In [65]:
processor_gnrtn_dict={
    '10th':110, 'Not Available':120, '11th':130, '7th':140, '8th':150, '9th':160, '4th':170, '12th':180
}
df['processor_gnrtn']=df['processor_gnrtn'].map(processor_gnrtn_dict)

In [66]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,warranty,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,1,10,110,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,No warranty,No,34649,2 stars,3,0
1,Lenovo,1,10,110,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,No warranty,No,38999,3 stars,65,5
2,Lenovo,1,10,110,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,No warranty,No,39999,3 stars,8,1
3,ASUS,1,20,110,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,No warranty,No,69990,3 stars,0,0
4,ASUS,1,30,120,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,No warranty,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,2,111,120,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,1 year,No,135990,3 stars,0,0
819,ASUS,2,111,120,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,1 year,No,144990,3 stars,0,0
820,ASUS,2,111,120,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,1 year,No,149990,3 stars,0,0
821,ASUS,2,111,120,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,1 year,No,142990,3 stars,0,0
822,Lenovo,2,40,110,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,No warranty,No,57490,4 stars,18,4

In [67]:
df['ram_gb'].unique()

<StringArray>
['4 GB', '8 GB', '16 GB', '32 GB']
Length: 4, dtype: str

In [68]:
ram_gb_dict={
    '4 GB':210, '8 GB':220, '16 GB':230, '32 GB':240
}
df['ram_gb']=df['ram_gb'].map(ram_gb_dict)

In [69]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,warranty,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,1,10,110,210,DDR4,0 GB,1024 GB,Windows,64-bit,No warranty,No,34649,2 stars,3,0
1,Lenovo,1,10,110,210,DDR4,0 GB,1024 GB,Windows,64-bit,No warranty,No,38999,3 stars,65,5
2,Lenovo,1,10,110,210,DDR4,0 GB,1024 GB,Windows,64-bit,No warranty,No,39999,3 stars,8,1
3,ASUS,1,20,110,220,DDR4,512 GB,0 GB,Windows,32-bit,No warranty,No,69990,3 stars,0,0
4,ASUS,1,30,120,210,DDR4,0 GB,512 GB,Windows,64-bit,No warranty,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,2,111,120,210,DDR4,1024 GB,0 GB,Windows,64-bit,1 year,No,135990,3 stars,0,0
819,ASUS,2,111,120,210,DDR4,1024 GB,0 GB,Windows,64-bit,1 year,No,144990,3 stars,0,0
820,ASUS,2,111,120,210,DDR4,1024 GB,0 GB,Windows,64-bit,1 year,No,149990,3 stars,0,0
821,ASUS,2,111,120,210,DDR4,1024 GB,0 GB,Windows,64-bit,1 year,No,142990,3 stars,0,0
822,Lenovo,2,40,110,220,DDR4,512 GB,0 GB,DOS,64-bit,No warranty,No,57490,4 stars,18,4

In [70]:
df['brand'].unique()

<StringArray>
['ASUS', 'Lenovo', 'acer', 'Avita', 'HP', 'DELL', 'MSI', 'APPLE']
Length: 8, dtype: str

In [71]:
brand_dict={
    'ASUS':310, 'Lenovo':320, 'acer':330, 'Avita':340, 'HP':350, 'DELL':360, 'MSI':370, 'APPLE':380
}
df['brand']=df['brand'].map(brand_dict)

In [72]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,warranty,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,310,1,10,110,210,DDR4,0 GB,1024 GB,Windows,64-bit,No warranty,No,34649,2 stars,3,0
1,320,1,10,110,210,DDR4,0 GB,1024 GB,Windows,64-bit,No warranty,No,38999,3 stars,65,5
2,320,1,10,110,210,DDR4,0 GB,1024 GB,Windows,64-bit,No warranty,No,39999,3 stars,8,1
3,310,1,20,110,220,DDR4,512 GB,0 GB,Windows,32-bit,No warranty,No,69990,3 stars,0,0
4,310,1,30,120,210,DDR4,0 GB,512 GB,Windows,64-bit,No warranty,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,310,2,111,120,210,DDR4,1024 GB,0 GB,Windows,64-bit,1 year,No,135990,3 stars,0,0
819,310,2,111,120,210,DDR4,1024 GB,0 GB,Windows,64-bit,1 year,No,144990,3 stars,0,0
820,310,2,111,120,210,DDR4,1024 GB,0 GB,Windows,64-bit,1 year,No,149990,3 stars,0,0
821,310,2,111,120,210,DDR4,1024 GB,0 GB,Windows,64-bit,1 year,No,142990,3 stars,0,0
822,320,2,40,110,220,DDR4,512 GB,0 GB,DOS,64-bit,No warranty,No,57490,4 stars,18,4

In [73]:
df['ram_type'].unique()

<StringArray>
['DDR4', 'LPDDR4', 'LPDDR4X', 'DDR5', 'DDR3', 'LPDDR3']
Length: 6, dtype: str

In [74]:
ram_type_dict={
    'DDR4':400, 'LPDDR4':410, 'LPDDR4X':420, 'DDR5':430, 'DDR3':440, 'LPDDR3':450
}
df['ram_type']=df['ram_type'].map(ram_type_dict)

In [75]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,warranty,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,310,1,10,110,210,400,0 GB,1024 GB,Windows,64-bit,No warranty,No,34649,2 stars,3,0
1,320,1,10,110,210,400,0 GB,1024 GB,Windows,64-bit,No warranty,No,38999,3 stars,65,5
2,320,1,10,110,210,400,0 GB,1024 GB,Windows,64-bit,No warranty,No,39999,3 stars,8,1
3,310,1,20,110,220,400,512 GB,0 GB,Windows,32-bit,No warranty,No,69990,3 stars,0,0
4,310,1,30,120,210,400,0 GB,512 GB,Windows,64-bit,No warranty,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,310,2,111,120,210,400,1024 GB,0 GB,Windows,64-bit,1 year,No,135990,3 stars,0,0
819,310,2,111,120,210,400,1024 GB,0 GB,Windows,64-bit,1 year,No,144990,3 stars,0,0
820,310,2,111,120,210,400,1024 GB,0 GB,Windows,64-bit,1 year,No,149990,3 stars,0,0
821,310,2,111,120,210,400,1024 GB,0 GB,Windows,64-bit,1 year,No,142990,3 stars,0,0
822,320,2,40,110,220,400,512 GB,0 GB,DOS,64-bit,No warranty,No,57490,4 stars,18,4

In [76]:
df['ssd'].unique()

<StringArray>
['0 GB', '512 GB', '256 GB', '128 GB', '1024 GB', '2048 GB', '3072 GB']
Length: 7, dtype: str

In [77]:
ssd_dict={
    '0 GB':0, '512 GB':512, '256 GB':256, '128 GB':128, '1024 GB':1024, '2048 GB':2048, '3072 GB':3072
}
df['ssd']=df['ssd'].map(ssd_dict)

In [78]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,warranty,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,310,1,10,110,210,400,0,1024 GB,Windows,64-bit,No warranty,No,34649,2 stars,3,0
1,320,1,10,110,210,400,0,1024 GB,Windows,64-bit,No warranty,No,38999,3 stars,65,5
2,320,1,10,110,210,400,0,1024 GB,Windows,64-bit,No warranty,No,39999,3 stars,8,1
3,310,1,20,110,220,400,512,0 GB,Windows,32-bit,No warranty,No,69990,3 stars,0,0
4,310,1,30,120,210,400,0,512 GB,Windows,64-bit,No warranty,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,310,2,111,120,210,400,1024,0 GB,Windows,64-bit,1 year,No,135990,3 stars,0,0
819,310,2,111,120,210,400,1024,0 GB,Windows,64-bit,1 year,No,144990,3 stars,0,0
820,310,2,111,120,210,400,1024,0 GB,Windows,64-bit,1 year,No,149990,3 stars,0,0
821,310,2,111,120,210,400,1024,0 GB,Windows,64-bit,1 year,No,142990,3 stars,0,0
822,320,2,40,110,220,400,512,0 GB,DOS,64-bit,No warranty,No,57490,4 stars,18,4

In [79]:
df['hdd'].unique()

<StringArray>
['1024 GB', '0 GB', '512 GB', '2048 GB']
Length: 4, dtype: str

In [80]:
hdd_dict={
    '1024 GB':1024, '0 GB':0, '512 GB':512, '2048 GB':2048
}
df['hdd']=df['hdd'].map(hdd_dict)

In [81]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,warranty,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,310,1,10,110,210,400,0,1024,Windows,64-bit,No warranty,No,34649,2 stars,3,0
1,320,1,10,110,210,400,0,1024,Windows,64-bit,No warranty,No,38999,3 stars,65,5
2,320,1,10,110,210,400,0,1024,Windows,64-bit,No warranty,No,39999,3 stars,8,1
3,310,1,20,110,220,400,512,0,Windows,32-bit,No warranty,No,69990,3 stars,0,0
4,310,1,30,120,210,400,0,512,Windows,64-bit,No warranty,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,310,2,111,120,210,400,1024,0,Windows,64-bit,1 year,No,135990,3 stars,0,0
819,310,2,111,120,210,400,1024,0,Windows,64-bit,1 year,No,144990,3 stars,0,0
820,310,2,111,120,210,400,1024,0,Windows,64-bit,1 year,No,149990,3 stars,0,0
821,310,2,111,120,210,400,1024,0,Windows,64-bit,1 year,No,142990,3 stars,0,0
822,320,2,40,110,220,400,512,0,DOS,64-bit,No warranty,No,57490,4 stars,18,4

In [82]:
df['os'].unique()

<StringArray>
['Windows', 'DOS', 'Mac']
Length: 3, dtype: str

In [83]:
os_dict={
'Windows':500, 'DOS':510, 'Mac':520
}
df['os']=df['os'].map(os_dict)

In [84]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,warranty,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,310,1,10,110,210,400,0,1024,500,64-bit,No warranty,No,34649,2 stars,3,0
1,320,1,10,110,210,400,0,1024,500,64-bit,No warranty,No,38999,3 stars,65,5
2,320,1,10,110,210,400,0,1024,500,64-bit,No warranty,No,39999,3 stars,8,1
3,310,1,20,110,220,400,512,0,500,32-bit,No warranty,No,69990,3 stars,0,0
4,310,1,30,120,210,400,0,512,500,64-bit,No warranty,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,310,2,111,120,210,400,1024,0,500,64-bit,1 year,No,135990,3 stars,0,0
819,310,2,111,120,210,400,1024,0,500,64-bit,1 year,No,144990,3 stars,0,0
820,310,2,111,120,210,400,1024,0,500,64-bit,1 year,No,149990,3 stars,0,0
821,310,2,111,120,210,400,1024,0,500,64-bit,1 year,No,142990,3 stars,0,0
822,320,2,40,110,220,400,512,0,510,64-bit,No warranty,No,57490,4 stars,18,4

In [85]:
df['os_bit'].unique()

<StringArray>
['64-bit', '32-bit']
Length: 2, dtype: str

In [86]:
os_bit_dict={
'64-bit':64, '32-bit':32
}
df['os_bit']=df['os_bit'].map(os_bit_dict)

In [87]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,warranty,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,310,1,10,110,210,400,0,1024,500,64,No warranty,No,34649,2 stars,3,0
1,320,1,10,110,210,400,0,1024,500,64,No warranty,No,38999,3 stars,65,5
2,320,1,10,110,210,400,0,1024,500,64,No warranty,No,39999,3 stars,8,1
3,310,1,20,110,220,400,512,0,500,32,No warranty,No,69990,3 stars,0,0
4,310,1,30,120,210,400,0,512,500,64,No warranty,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,310,2,111,120,210,400,1024,0,500,64,1 year,No,135990,3 stars,0,0
819,310,2,111,120,210,400,1024,0,500,64,1 year,No,144990,3 stars,0,0
820,310,2,111,120,210,400,1024,0,500,64,1 year,No,149990,3 stars,0,0
821,310,2,111,120,210,400,1024,0,500,64,1 year,No,142990,3 stars,0,0
822,320,2,40,110,220,400,512,0,510,64,No warranty,No,57490,4 stars,18,4

In [88]:
df['warranty'].unique()

<StringArray>
['No warranty', '1 year', '2 years', '3 years']
Length: 4, dtype: str

In [89]:
warranty_dict={
'No warranty':0, '1 year':1, '2 years':2, '3 years':3
}
df['warranty']=df['warranty'].map(warranty_dict)

In [90]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,warranty,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,310,1,10,110,210,400,0,1024,500,64,0,No,34649,2 stars,3,0
1,320,1,10,110,210,400,0,1024,500,64,0,No,38999,3 stars,65,5
2,320,1,10,110,210,400,0,1024,500,64,0,No,39999,3 stars,8,1
3,310,1,20,110,220,400,512,0,500,32,0,No,69990,3 stars,0,0
4,310,1,30,120,210,400,0,512,500,64,0,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,310,2,111,120,210,400,1024,0,500,64,1,No,135990,3 stars,0,0
819,310,2,111,120,210,400,1024,0,500,64,1,No,144990,3 stars,0,0
820,310,2,111,120,210,400,1024,0,500,64,1,No,149990,3 stars,0,0
821,310,2,111,120,210,400,1024,0,500,64,1,No,142990,3 stars,0,0
822,320,2,40,110,220,400,512,0,510,64,0,No,57490,4 stars,18,4

In [91]:
df['msoffice'].unique()

<StringArray>
['No', 'Yes']
Length: 2, dtype: str

In [92]:
msoffice_dict={
'No':0, 'Yes':1
}
df['msoffice']=df['msoffice'].map(msoffice_dict)

In [93]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,warranty,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,310,1,10,110,210,400,0,1024,500,64,0,0,34649,2 stars,3,0
1,320,1,10,110,210,400,0,1024,500,64,0,0,38999,3 stars,65,5
2,320,1,10,110,210,400,0,1024,500,64,0,0,39999,3 stars,8,1
3,310,1,20,110,220,400,512,0,500,32,0,0,69990,3 stars,0,0
4,310,1,30,120,210,400,0,512,500,64,0,0,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,310,2,111,120,210,400,1024,0,500,64,1,0,135990,3 stars,0,0
819,310,2,111,120,210,400,1024,0,500,64,1,0,144990,3 stars,0,0
820,310,2,111,120,210,400,1024,0,500,64,1,0,149990,3 stars,0,0
821,310,2,111,120,210,400,1024,0,500,64,1,0,142990,3 stars,0,0
822,320,2,40,110,220,400,512,0,510,64,0,0,57490,4 stars,18,4

In [94]:
df['rating'].unique()

<StringArray>
['2 stars', '3 stars', '4 stars', '5 stars', '1 star']
Length: 5, dtype: str

In [95]:
rating_dict={
'1 star':1, '2 stars':2, '3 stars':3, '4 stars':4, '5 stars':5
}
df['rating']=df['rating'].map(rating_dict)

In [96]:
df.info()

<class 'pandas.DataFrame'>
Index: 802 entries, 0 to 822
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   brand              802 non-null    int64
 1   processor_brand    802 non-null    int64
 2   processor_name     802 non-null    int64
 3   processor_gnrtn    802 non-null    int64
 4   ram_gb             802 non-null    int64
 5   ram_type           802 non-null    int64
 6   ssd                802 non-null    int64
 7   hdd                802 non-null    int64
 8   os                 802 non-null    int64
 9   os_bit             802 non-null    int64
 10  warranty           802 non-null    int64
 11  msoffice           802 non-null    int64
 12  Price              802 non-null    int64
 13  rating             802 non-null    int64
 14  Number of Ratings  802 non-null    int64
 15  Number of Reviews  802 non-null    int64
dtypes: int64(16)
memory usage: 106.5 KB

In [97]:
x=df.drop('Price', axis=1)

In [98]:
x

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,warranty,msoffice,rating,Number of Ratings,Number of Reviews
0,310,1,10,110,210,400,0,1024,500,64,0,0,2,3,0
1,320,1,10,110,210,400,0,1024,500,64,0,0,3,65,5
2,320,1,10,110,210,400,0,1024,500,64,0,0,3,8,1
3,310,1,20,110,220,400,512,0,500,32,0,0,3,0,0
4,310,1,30,120,210,400,0,512,500,64,0,0,3,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,310,2,111,120,210,400,1024,0,500,64,1,0,3,0,0
819,310,2,111,120,210,400,1024,0,500,64,1,0,3,0,0
820,310,2,111,120,210,400,1024,0,500,64,1,0,3,0,0
821,310,2,111,120,210,400,1024,0,500,64,1,0,3,0,0
822,320,2,40,110,220,400,512,0,510,64,0,0,4,18,4

In [99]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,warranty,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,310,1,10,110,210,400,0,1024,500,64,0,0,34649,2,3,0
1,320,1,10,110,210,400,0,1024,500,64,0,0,38999,3,65,5
2,320,1,10,110,210,400,0,1024,500,64,0,0,39999,3,8,1
3,310,1,20,110,220,400,512,0,500,32,0,0,69990,3,0,0
4,310,1,30,120,210,400,0,512,500,64,0,0,26990,3,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,310,2,111,120,210,400,1024,0,500,64,1,0,135990,3,0,0
819,310,2,111,120,210,400,1024,0,500,64,1,0,144990,3,0,0
820,310,2,111,120,210,400,1024,0,500,64,1,0,149990,3,0,0
821,310,2,111,120,210,400,1024,0,500,64,1,0,142990,3,0,0
822,320,2,40,110,220,400,512,0,510,64,0,0,57490,4,18,4

In [100]:
# df.duplicated().sum()

In [101]:
# df.drop_duplicates(inplace=True)

In [102]:
# df.duplicated().sum()

In [103]:
# df.isnull().sum()

In [104]:
# df.isnull().sum()

In [105]:
x =df.drop('Price', axis=1)

In [106]:
y =df[['Price']]

In [107]:
y

      Price
0     34649
1     38999
2     39999
3     69990
4     26990
..      ...
818  135990
819  144990
820  149990
821  142990
822   57490

[802 rows x 1 columns]

In [108]:
df.to_csv('clean_laptop.csv')

In [109]:
x

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,warranty,msoffice,rating,Number of Ratings,Number of Reviews
0,310,1,10,110,210,400,0,1024,500,64,0,0,2,3,0
1,320,1,10,110,210,400,0,1024,500,64,0,0,3,65,5
2,320,1,10,110,210,400,0,1024,500,64,0,0,3,8,1
3,310,1,20,110,220,400,512,0,500,32,0,0,3,0,0
4,310,1,30,120,210,400,0,512,500,64,0,0,3,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,310,2,111,120,210,400,1024,0,500,64,1,0,3,0,0
819,310,2,111,120,210,400,1024,0,500,64,1,0,3,0,0
820,310,2,111,120,210,400,1024,0,500,64,1,0,3,0,0
821,310,2,111,120,210,400,1024,0,500,64,1,0,3,0,0
822,320,2,40,110,220,400,512,0,510,64,0,0,4,18,4

In [110]:
y

      Price
0     34649
1     38999
2     39999
3     69990
4     26990
..      ...
818  135990
819  144990
820  149990
821  142990
822   57490

[802 rows x 1 columns]

In [111]:
import sklearn as sns
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC, SVR

In [112]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train ,y_test =train_test_split(x , y , test_size=0.2, random_state= 42)

In [113]:
print(x_train.shape, x_test.shape , y_train.shape ,y_test.shape)

(641, 15) (161, 15) (641, 1) (161, 1)

In [114]:
x_train

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,warranty,msoffice,rating,Number of Ratings,Number of Reviews
442,310,1,20,130,220,400,256,1024,500,32,1,1,4,1188,127
598,310,1,50,110,230,420,0,512,510,32,0,0,3,2,1
452,310,1,20,130,220,400,256,1024,500,64,1,1,4,33,4
696,360,2,40,120,220,400,512,0,500,64,1,1,3,0,0
339,310,1,20,130,220,420,512,0,500,64,1,0,4,35,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,320,1,10,110,210,400,256,0,500,32,0,0,3,3,0
108,360,1,10,130,220,400,512,0,500,64,1,0,4,10,1
275,320,1,20,110,220,400,512,0,500,64,1,1,3,0,0
445,310,1,20,130,220,400,256,1024,500,64,1,0,3,0,0
104,310,1,10,130,220,400,512,0,500,64,1,1,4,2058,305

In [115]:
y_train

      Price
442   50990
598  146490
452   60190
696   59490
339   99990
..      ...
73    41990
108   60790
275   57500
445   52990
104   44990

[641 rows x 1 columns]

In [116]:
x_test

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,warranty,msoffice,rating,Number of Ratings,Number of Reviews
196,330,1,20,120,220,430,0,512,500,32,0,0,4,10966,1185
299,310,1,20,130,220,420,512,0,500,32,1,1,4,76,14
171,360,1,10,110,220,400,256,1024,500,64,1,1,5,7,5
537,350,1,50,110,230,400,1024,0,500,64,1,1,4,17,4
551,370,1,50,130,230,400,1024,0,500,64,2,0,4,14,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
368,310,1,20,130,220,420,512,0,500,64,1,0,3,0,0
361,350,1,20,110,220,400,512,0,500,64,1,0,5,2,1
446,360,1,20,130,220,400,256,1024,500,64,1,0,4,47,0
767,320,2,100,120,210,400,512,0,500,64,1,0,3,0,0
529,320,1,50,130,230,400,512,0,500,32,0,0,3,0,0

In [117]:
y_test

      Price
196   50990
299   72990
171   41490
537  144690
551  129990
..      ...
368  114990
361  126000
446   57990
767  106990
529  110999

[161 rows x 1 columns]

In [118]:
from sklearn.linear_model import LinearRegression
lr =LinearRegression()

In [119]:
# df.columns = df.columns.str.lower().str.strip()

# X = df.drop('price', axis=1)
# y = df['price']

# X = pd.get_dummies(X, drop_first=True)

# from sklearn.model_selection import train_test_split

# X_train, X_test, y_train, y_test = train_test_split(
#     X, y, test_size=0.2, random_state=42
# )

from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(x_train, y_train)

LinearRegression()

In [120]:
lr.predict(x_test)

array([[ 39069.823629  ],
       [ 90103.58016053],
       [ 54141.68414131],
       [130715.03465085],
       [145756.80090958],
       [126525.44804137],
       [130544.02024216],
       [105836.31273539],
       [ 70297.37991743],
       [ 90745.72149366],
       [ 43934.38774639],
       [ 43560.25478901],
       [ 85575.8564157 ],
       [122545.45781835],
       [ 68007.32492119],
       [ 91510.26954007],
       [ 63986.19099996],
       [ 65783.56300164],
       [ 77856.24520825],
       [145776.63009975],
       [ 36182.05828699],
       [ 33750.15973076],
       [ 69355.21668332],
       [ 64925.02362105],
       [ 24726.47350824],
       [ 49712.8430603 ],
       [ 60929.52760223],
       [133028.91044461],
       [ 56973.38315254],
       [ 32273.68197024],
       [ 68474.62124499],
       [ 64513.53834427],
       [ 65591.22083586],
       [ 65909.57021589],
       [ 66039.72446913],
       [ 26743.40047533],
       [186025.28517536],
       [ 82451.09763599],
       [ 30582.24098618],
       [ 70017.91735873],
       [ 23344.66334619],
       [ 58188.83351912],
       [ 58270.80960274],
       [ 45757.66752291],
       [131196.17170674],
       [ 52463.08175464],
       [135349.6802851 ],
       [ 75790.20776672],
       [107826.16018243],
       [104810.89471077],
       [121472.76067083],
       [ 96187.73697927],
       [ 94599.01918086],
       [ 66524.13987477],
       [ 68256.19933251],
       [150271.06733609],
       [108557.75183529],
       [ 63053.77224307],
       [ 87815.29885553],
       [142247.01375787],
       [ 71884.57853949],
       [ 55537.8832902 ],
       [ 40510.78468887],
       [ 53420.34843807],
       [ 58296.83327689],
       [ 64118.22383446],
       [145754.73608159],
       [ 36702.21081065],
       [ 39924.57622243],
       [ 41188.54593908],
       [150084.94011471],
       [135985.45588783],
       [109545.95984228],
       [122545.45781835],
       [ 44216.02546175],
       [ 42773.75939858],
       [154481.00039063],
       [ 98343.81982613],
       [ 68997.38763022],
       [ 49640.68713128],
       [ 51692.48470519],
       [ 50005.67749303],
       [ 58427.33802607],
       [ 43934.38774639],
       [ 31931.93449748],
       [ 57422.08188568],
       [106942.61830619],
       [ 90164.02163112],
       [ 65375.16917418],
       [131171.31941582],
       [ 69624.33315899],
       [ 66231.07417301],
       [ 87175.5215947 ],
       [ 63632.49363273],
       [ 69634.10830949],
       [ 90146.25726894],
       [223693.59371155],
       [ 85575.8564157 ],
       [ 63492.52892758],
       [ 67200.98727444],
       [ 65702.71875594],
       [ 52586.88921674],
       [100671.04732963],
       [ 59181.4057655 ],
       [ 81307.0613748 ],
       [ 75971.4766527 ],
       [ 65447.93935759],
       [ 89614.12160248],
       [ 31642.66101391],
       [ 86928.47501579],
       [ 68506.53858246],
       [114765.3085755 ],
       [ 72108.74422174],
       [ 68180.92971736],
       [ 46975.44919137],
       [ 66216.64450015],
       [ 59817.32791413],
       [ 19991.19450661],
       [ 67621.11962534],
       [ 65684.19873867],
       [153973.35786629],
       [ 75954.35351514],
       [ 69902.51680411],
       [ 79829.02045357],
       [ 73222.05237653],
       [ 69552.17721388],
       [ 41170.02968489],
       [ 70478.18087366],
       [165097.17423404],
       [ 42020.50271563],
       [ 65811.88799355],
       [ 73036.11674936],
       [ 89042.58835487],
       [157530.76992899],
       [ 43153.30855034],
       [ 70522.7562757 ],
       [150985.80309354],
       [121894.52166844],
       [ 48614.87549621],
       [ 73598.0198023 ],
       [141685.24429173],
       [ 52218.47190497],
       [ 57571.66738226],
       [ 87941.82657365],
       [ 72779.87473765],
       [152484.40462251],
       [ 52998.90581584],
       [ 23838.55253525],
       [ 65871.14427184],
       [ 57862.442597  ],
       [ 67683.05876712],
       [117881.62508533],
       [ 57811.92539787],
       [ 26077.05834092],
       [ 79233.03348372],
       [145856.78444969],
       [ 87175.5215947 ],
       [ 63992.87676354],
       [ 70868.57954481],
       [ 74995.84886752],
       [104559.54160858]])

In [121]:
# lr.fit(X_train, y_train)
x_train

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,warranty,msoffice,rating,Number of Ratings,Number of Reviews
442,310,1,20,130,220,400,256,1024,500,32,1,1,4,1188,127
598,310,1,50,110,230,420,0,512,510,32,0,0,3,2,1
452,310,1,20,130,220,400,256,1024,500,64,1,1,4,33,4
696,360,2,40,120,220,400,512,0,500,64,1,1,3,0,0
339,310,1,20,130,220,420,512,0,500,64,1,0,4,35,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,320,1,10,110,210,400,256,0,500,32,0,0,3,3,0
108,360,1,10,130,220,400,512,0,500,64,1,0,4,10,1
275,320,1,20,110,220,400,512,0,500,64,1,1,3,0,0
445,310,1,20,130,220,400,256,1024,500,64,1,0,3,0,0
104,310,1,10,130,220,400,512,0,500,64,1,1,4,2058,305

In [122]:
x_test

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,warranty,msoffice,rating,Number of Ratings,Number of Reviews
196,330,1,20,120,220,430,0,512,500,32,0,0,4,10966,1185
299,310,1,20,130,220,420,512,0,500,32,1,1,4,76,14
171,360,1,10,110,220,400,256,1024,500,64,1,1,5,7,5
537,350,1,50,110,230,400,1024,0,500,64,1,1,4,17,4
551,370,1,50,130,230,400,1024,0,500,64,2,0,4,14,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
368,310,1,20,130,220,420,512,0,500,64,1,0,3,0,0
361,350,1,20,110,220,400,512,0,500,64,1,0,5,2,1
446,360,1,20,130,220,400,256,1024,500,64,1,0,4,47,0
767,320,2,100,120,210,400,512,0,500,64,1,0,3,0,0
529,320,1,50,130,230,400,512,0,500,32,0,0,3,0,0

In [123]:
from sklearn.ensemble import RandomForestRegressor
rgf =RandomForestRegressor(n_estimators=100, random_state=42)
rgf.fit(x_train, y_train)
pred =rgf.predict(x_test)

e:\Data science\Projects\Laptop\Laptop_price\Lib\site-packages\sklearn\base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

In [124]:
pred

array([ 72355.45      ,  86042.57      ,  41361.29      , 155044.03      ,
       153315.65083333, 163295.48666667,  99542.66666667,  93998.92428571,
        60603.59      , 141045.89857143,  37909.71      ,  43425.14      ,
        67904.51466667, 139620.76642857,  76315.74      , 118558.08      ,
        75190.89      ,  41046.64      ,  71528.19      , 157239.45916667,
        40759.6       ,  39755.87      ,  73414.12      ,  46709.72      ,
        40345.25      ,  49641.71      ,  55848.03      , 210579.35666667,
        70665.75      ,  39507.54666667,  58784.22      ,  69203.07      ,
        44338.38      ,  73661.41857143,  70761.60357143,  38110.48      ,
       153483.18      ,  68882.48      ,  41822.71      ,  67887.37      ,
        39998.55      ,  56376.28      ,  54494.07      ,  39887.29      ,
       130348.33333333,  59331.68      , 164534.81      ,  76604.825     ,
        78349.88      , 111864.36      , 187676.71      , 128603.68      ,
       128034.04      ,  67648.19      ,  68793.46      , 109450.85333333,
        78952.38      ,  44471.        , 108213.71      , 180136.46666667,
        73298.18      ,  35287.52333333,  39817.7       ,  60808.26      ,
        61729.21      ,  65985.92      , 152977.65083333,  44908.17      ,
        40581.9       ,  42069.74      , 100303.65      , 135128.04      ,
       143235.        , 139620.76642857,  43461.74      ,  40718.5       ,
       156600.        ,  86052.98666667,  58495.34      ,  54631.16      ,
        54926.        ,  60116.15      ,  67758.49041667,  37909.71      ,
        40977.38      ,  55391.33      ,  90913.37902381,  98079.0995    ,
        65231.34      , 140799.47234127,  73501.78083333,  61556.92      ,
        87210.47333333,  56661.83      ,  59960.70333333,  94959.6495    ,
       176404.1       ,  67904.51466667,  40976.4       ,  65012.155     ,
        40987.62      ,  41050.65619048,  96900.03997619,  52402.79      ,
        57132.03333333,  69788.06      ,  51096.76      , 100493.93      ,
        39976.15619048,  84022.3       ,  71678.77      , 114292.58      ,
        63047.105     ,  61305.25      ,  66449.38      ,  62283.52      ,
        38319.09      ,  64488.6       ,  57311.23      ,  47131.9       ,
       125136.66983333,  72043.08      ,  57065.46      ,  67473.        ,
        93417.82      ,  79787.845     ,  39731.9       ,  61035.415     ,
       178950.        ,  44473.07333333,  58447.79      ,  66270.19      ,
        81725.52      , 156632.15916667,  43357.26      ,  60671.85125   ,
       151424.28666667,  99763.8       ,  71125.05857143,  65658.66375   ,
       144577.45      ,  40359.94      ,  61241.66      ,  96782.34333333,
        66339.21      , 118367.36583333,  63696.4667381 ,  51823.56      ,
        46467.49      ,  51854.83      ,  67380.68      , 142197.9143254 ,
        60856.36      ,  38389.56666667,  54265.22      , 141243.23916667,
        87210.47333333,  68812.68      ,  62874.27      ,  78687.195     ,
        91818.18083333])

In [125]:
y_test

      Price
196   50990
299   72990
171   41490
537  144690
551  129990
..      ...
368  114990
361  126000
446   57990
767  106990
529  110999

[161 rows x 1 columns]

In [126]:
pred =lr.predict(x_test)

In [127]:
lst = [[330,	1,	20,	120,	220,	430,	0,	512,	500,	32,	0,	0,	4,	10966,	1185]]
lr.predict(lst)

e:\Data science\Projects\Laptop\Laptop_price\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[39069.823629]])

In [128]:
lr.score(x_test, y_test)

0.5393282739733353

In [129]:
lr.score(x_train, y_train)

0.6769671131919444

In [130]:
pred

array([[ 39069.823629  ],
       [ 90103.58016053],
       [ 54141.68414131],
       [130715.03465085],
       [145756.80090958],
       [126525.44804137],
       [130544.02024216],
       [105836.31273539],
       [ 70297.37991743],
       [ 90745.72149366],
       [ 43934.38774639],
       [ 43560.25478901],
       [ 85575.8564157 ],
       [122545.45781835],
       [ 68007.32492119],
       [ 91510.26954007],
       [ 63986.19099996],
       [ 65783.56300164],
       [ 77856.24520825],
       [145776.63009975],
       [ 36182.05828699],
       [ 33750.15973076],
       [ 69355.21668332],
       [ 64925.02362105],
       [ 24726.47350824],
       [ 49712.8430603 ],
       [ 60929.52760223],
       [133028.91044461],
       [ 56973.38315254],
       [ 32273.68197024],
       [ 68474.62124499],
       [ 64513.53834427],
       [ 65591.22083586],
       [ 65909.57021589],
       [ 66039.72446913],
       [ 26743.40047533],
       [186025.28517536],
       [ 82451.09763599],
       [ 30582.24098618],
       [ 70017.91735873],
       [ 23344.66334619],
       [ 58188.83351912],
       [ 58270.80960274],
       [ 45757.66752291],
       [131196.17170674],
       [ 52463.08175464],
       [135349.6802851 ],
       [ 75790.20776672],
       [107826.16018243],
       [104810.89471077],
       [121472.76067083],
       [ 96187.73697927],
       [ 94599.01918086],
       [ 66524.13987477],
       [ 68256.19933251],
       [150271.06733609],
       [108557.75183529],
       [ 63053.77224307],
       [ 87815.29885553],
       [142247.01375787],
       [ 71884.57853949],
       [ 55537.8832902 ],
       [ 40510.78468887],
       [ 53420.34843807],
       [ 58296.83327689],
       [ 64118.22383446],
       [145754.73608159],
       [ 36702.21081065],
       [ 39924.57622243],
       [ 41188.54593908],
       [150084.94011471],
       [135985.45588783],
       [109545.95984228],
       [122545.45781835],
       [ 44216.02546175],
       [ 42773.75939858],
       [154481.00039063],
       [ 98343.81982613],
       [ 68997.38763022],
       [ 49640.68713128],
       [ 51692.48470519],
       [ 50005.67749303],
       [ 58427.33802607],
       [ 43934.38774639],
       [ 31931.93449748],
       [ 57422.08188568],
       [106942.61830619],
       [ 90164.02163112],
       [ 65375.16917418],
       [131171.31941582],
       [ 69624.33315899],
       [ 66231.07417301],
       [ 87175.5215947 ],
       [ 63632.49363273],
       [ 69634.10830949],
       [ 90146.25726894],
       [223693.59371155],
       [ 85575.8564157 ],
       [ 63492.52892758],
       [ 67200.98727444],
       [ 65702.71875594],
       [ 52586.88921674],
       [100671.04732963],
       [ 59181.4057655 ],
       [ 81307.0613748 ],
       [ 75971.4766527 ],
       [ 65447.93935759],
       [ 89614.12160248],
       [ 31642.66101391],
       [ 86928.47501579],
       [ 68506.53858246],
       [114765.3085755 ],
       [ 72108.74422174],
       [ 68180.92971736],
       [ 46975.44919137],
       [ 66216.64450015],
       [ 59817.32791413],
       [ 19991.19450661],
       [ 67621.11962534],
       [ 65684.19873867],
       [153973.35786629],
       [ 75954.35351514],
       [ 69902.51680411],
       [ 79829.02045357],
       [ 73222.05237653],
       [ 69552.17721388],
       [ 41170.02968489],
       [ 70478.18087366],
       [165097.17423404],
       [ 42020.50271563],
       [ 65811.88799355],
       [ 73036.11674936],
       [ 89042.58835487],
       [157530.76992899],
       [ 43153.30855034],
       [ 70522.7562757 ],
       [150985.80309354],
       [121894.52166844],
       [ 48614.87549621],
       [ 73598.0198023 ],
       [141685.24429173],
       [ 52218.47190497],
       [ 57571.66738226],
       [ 87941.82657365],
       [ 72779.87473765],
       [152484.40462251],
       [ 52998.90581584],
       [ 23838.55253525],
       [ 65871.14427184],
       [ 57862.442597  ],
       [ 67683.05876712],
       [117881.62508533],
       [ 57811.92539787],
       [ 26077.05834092],
       [ 79233.03348372],
       [145856.78444969],
       [ 87175.5215947 ],
       [ 63992.87676354],
       [ 70868.57954481],
       [ 74995.84886752],
       [104559.54160858]])

In [131]:
y_test

      Price
196   50990
299   72990
171   41490
537  144690
551  129990
..      ...
368  114990
361  126000
446   57990
767  106990
529  110999

[161 rows x 1 columns]

In [132]:
from sklearn.svm import SVR
sv=SVR()

In [133]:
lr.fit(x_train, y_train)

LinearRegression()

In [134]:
lr.predict(x_test)

array([[ 39069.823629  ],
       [ 90103.58016053],
       [ 54141.68414131],
       [130715.03465085],
       [145756.80090958],
       [126525.44804137],
       [130544.02024216],
       [105836.31273539],
       [ 70297.37991743],
       [ 90745.72149366],
       [ 43934.38774639],
       [ 43560.25478901],
       [ 85575.8564157 ],
       [122545.45781835],
       [ 68007.32492119],
       [ 91510.26954007],
       [ 63986.19099996],
       [ 65783.56300164],
       [ 77856.24520825],
       [145776.63009975],
       [ 36182.05828699],
       [ 33750.15973076],
       [ 69355.21668332],
       [ 64925.02362105],
       [ 24726.47350824],
       [ 49712.8430603 ],
       [ 60929.52760223],
       [133028.91044461],
       [ 56973.38315254],
       [ 32273.68197024],
       [ 68474.62124499],
       [ 64513.53834427],
       [ 65591.22083586],
       [ 65909.57021589],
       [ 66039.72446913],
       [ 26743.40047533],
       [186025.28517536],
       [ 82451.09763599],
       [ 30582.24098618],
       [ 70017.91735873],
       [ 23344.66334619],
       [ 58188.83351912],
       [ 58270.80960274],
       [ 45757.66752291],
       [131196.17170674],
       [ 52463.08175464],
       [135349.6802851 ],
       [ 75790.20776672],
       [107826.16018243],
       [104810.89471077],
       [121472.76067083],
       [ 96187.73697927],
       [ 94599.01918086],
       [ 66524.13987477],
       [ 68256.19933251],
       [150271.06733609],
       [108557.75183529],
       [ 63053.77224307],
       [ 87815.29885553],
       [142247.01375787],
       [ 71884.57853949],
       [ 55537.8832902 ],
       [ 40510.78468887],
       [ 53420.34843807],
       [ 58296.83327689],
       [ 64118.22383446],
       [145754.73608159],
       [ 36702.21081065],
       [ 39924.57622243],
       [ 41188.54593908],
       [150084.94011471],
       [135985.45588783],
       [109545.95984228],
       [122545.45781835],
       [ 44216.02546175],
       [ 42773.75939858],
       [154481.00039063],
       [ 98343.81982613],
       [ 68997.38763022],
       [ 49640.68713128],
       [ 51692.48470519],
       [ 50005.67749303],
       [ 58427.33802607],
       [ 43934.38774639],
       [ 31931.93449748],
       [ 57422.08188568],
       [106942.61830619],
       [ 90164.02163112],
       [ 65375.16917418],
       [131171.31941582],
       [ 69624.33315899],
       [ 66231.07417301],
       [ 87175.5215947 ],
       [ 63632.49363273],
       [ 69634.10830949],
       [ 90146.25726894],
       [223693.59371155],
       [ 85575.8564157 ],
       [ 63492.52892758],
       [ 67200.98727444],
       [ 65702.71875594],
       [ 52586.88921674],
       [100671.04732963],
       [ 59181.4057655 ],
       [ 81307.0613748 ],
       [ 75971.4766527 ],
       [ 65447.93935759],
       [ 89614.12160248],
       [ 31642.66101391],
       [ 86928.47501579],
       [ 68506.53858246],
       [114765.3085755 ],
       [ 72108.74422174],
       [ 68180.92971736],
       [ 46975.44919137],
       [ 66216.64450015],
       [ 59817.32791413],
       [ 19991.19450661],
       [ 67621.11962534],
       [ 65684.19873867],
       [153973.35786629],
       [ 75954.35351514],
       [ 69902.51680411],
       [ 79829.02045357],
       [ 73222.05237653],
       [ 69552.17721388],
       [ 41170.02968489],
       [ 70478.18087366],
       [165097.17423404],
       [ 42020.50271563],
       [ 65811.88799355],
       [ 73036.11674936],
       [ 89042.58835487],
       [157530.76992899],
       [ 43153.30855034],
       [ 70522.7562757 ],
       [150985.80309354],
       [121894.52166844],
       [ 48614.87549621],
       [ 73598.0198023 ],
       [141685.24429173],
       [ 52218.47190497],
       [ 57571.66738226],
       [ 87941.82657365],
       [ 72779.87473765],
       [152484.40462251],
       [ 52998.90581584],
       [ 23838.55253525],
       [ 65871.14427184],
       [ 57862.442597  ],
       [ 67683.05876712],
       [117881.62508533],
       [ 57811.92539787],
       [ 26077.05834092],
       [ 79233.03348372],
       [145856.78444969],
       [ 87175.5215947 ],
       [ 63992.87676354],
       [ 70868.57954481],
       [ 74995.84886752],
       [104559.54160858]])

In [135]:
sv.fit(x_train, y_train)

e:\Data science\Projects\Laptop\Laptop_price\Lib\site-packages\sklearn\utils\validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR()

In [136]:
pred=sv.predict(x_test)
pred

array([64027.41754686, 64085.05743949, 63998.33559126, 64114.01305765,
       64114.02910273, 64114.26569309, 64027.53259715, 64086.93241298,
       64084.86724603, 64053.53146741, 64065.63243916, 63981.01971171,
       64087.00114738, 64114.31076385, 64086.30978216, 64013.78436465,
       64086.94252306, 64085.9170897 , 64086.92515155, 64114.19661692,
       63979.99503443, 64065.65985288, 64086.66178662, 64064.08385577,
       64017.84013555, 64065.70379765, 64077.40390615, 64114.27311195,
       64064.95483217, 64065.67374581, 63997.85165546, 64085.90129439,
       63989.84925833, 64086.99123493, 64087.01157998, 64064.75187691,
       64084.2553053 , 64086.79162474, 64063.12347952, 64086.73966814,
       64045.78690227, 64067.87226781, 64086.08867922, 63985.70533281,
       64086.1446604 , 64065.66577343, 64114.07428333, 64087.33579111,
       64101.08960327, 63998.67594469, 64087.18516753, 64013.96503722,
       64013.94652279, 64087.037745  , 64080.97227326, 64114.36750191,
       64108.76183003, 64055.66130582, 64087.01275624, 64114.23527589,
       64012.07701797, 64014.22176792, 64021.64788729, 64021.38941648,
       64086.78625261, 64085.14144174, 64113.93264446, 64020.87120929,
       64013.89957276, 63985.19689174, 64114.24249789, 64108.91804849,
       64013.37729818, 64114.31076385, 64064.89316973, 64056.52025421,
       64086.24147208, 64087.35721105, 64052.19542885, 64086.01140356,
       64065.74171538, 63985.62334948, 63993.57462199, 64065.63243916,
       64064.60332785, 63998.21542506, 64087.18176645, 64087.08706467,
       64086.15704671, 64114.11536866, 64086.68585519, 64086.99128058,
       64087.00905589, 64082.91911517, 64087.31162424, 64086.9749925 ,
       64112.22440737, 64087.00114738, 64066.03841686, 64083.9049554 ,
       64020.825641  , 64065.65312531, 64087.28204801, 64075.6028637 ,
       64087.26863235, 64083.2967749 , 64086.54086743, 63998.01368299,
       64065.60843188, 64086.37731774, 64086.29985367, 64114.3486306 ,
       64080.70884375, 64083.14555492, 63985.53501091, 63998.36007806,
       64037.63945888, 64007.42940286, 64053.072152  , 64086.91274714,
       64114.28091061, 64086.83567668, 64076.66679832, 63998.36258884,
       64087.02169427, 64087.30412995, 64011.50688261, 64086.73603213,
       64114.2056717 , 64065.3866286 , 64031.02207135, 64086.54926825,
       64086.77702695, 64114.33841998, 64065.67724134, 63998.40153466,
       64114.28295441, 64086.49002359, 64087.11118136, 63998.40891642,
       64112.05095246, 63985.12013515, 64021.07365684, 63996.66308402,
       64086.29371848, 64114.26231623, 63986.0101004 , 63994.06457174,
       64078.95864673, 64080.78731821, 64085.3273365 , 64114.10003961,
       64014.46985556, 63985.78734294, 64087.09686666, 64114.34036514,
       64087.00905589, 64086.96117477, 63997.56686365, 64087.32359032,
       64087.16683429])

In [137]:
pred[0:100]

array([64027.41754686, 64085.05743949, 63998.33559126, 64114.01305765,
       64114.02910273, 64114.26569309, 64027.53259715, 64086.93241298,
       64084.86724603, 64053.53146741, 64065.63243916, 63981.01971171,
       64087.00114738, 64114.31076385, 64086.30978216, 64013.78436465,
       64086.94252306, 64085.9170897 , 64086.92515155, 64114.19661692,
       63979.99503443, 64065.65985288, 64086.66178662, 64064.08385577,
       64017.84013555, 64065.70379765, 64077.40390615, 64114.27311195,
       64064.95483217, 64065.67374581, 63997.85165546, 64085.90129439,
       63989.84925833, 64086.99123493, 64087.01157998, 64064.75187691,
       64084.2553053 , 64086.79162474, 64063.12347952, 64086.73966814,
       64045.78690227, 64067.87226781, 64086.08867922, 63985.70533281,
       64086.1446604 , 64065.66577343, 64114.07428333, 64087.33579111,
       64101.08960327, 63998.67594469, 64087.18516753, 64013.96503722,
       64013.94652279, 64087.037745  , 64080.97227326, 64114.36750191,
       64108.76183003, 64055.66130582, 64087.01275624, 64114.23527589,
       64012.07701797, 64014.22176792, 64021.64788729, 64021.38941648,
       64086.78625261, 64085.14144174, 64113.93264446, 64020.87120929,
       64013.89957276, 63985.19689174, 64114.24249789, 64108.91804849,
       64013.37729818, 64114.31076385, 64064.89316973, 64056.52025421,
       64086.24147208, 64087.35721105, 64052.19542885, 64086.01140356,
       64065.74171538, 63985.62334948, 63993.57462199, 64065.63243916,
       64064.60332785, 63998.21542506, 64087.18176645, 64087.08706467,
       64086.15704671, 64114.11536866, 64086.68585519, 64086.99128058,
       64087.00905589, 64082.91911517, 64087.31162424, 64086.9749925 ,
       64112.22440737, 64087.00114738, 64066.03841686, 64083.9049554 ])

In [138]:
sv.score(x_test, y_test)

-0.1305966056813248

In [139]:
lr

LinearRegression()

In [140]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(641, 15)
(641, 1)
(161, 15)
(161, 1)

In [141]:
y_train=y_train.values.ravel()

In [142]:
! pip install imbalanced-learn
import imblearn
from imblearn.over_sampling import SMOTE

Collecting imbalanced-learn
  Using cached imbalanced_learn-0.14.1-py3-none-any.whl.metadata (8.9 kB)
Requirement already satisfied: numpy<3,>=1.25.2 in e:\data science\projects\laptop\laptop_price\lib\site-packages (from imbalanced-learn) (2.4.2)
Requirement already satisfied: scipy<2,>=1.11.4 in e:\data science\projects\laptop\laptop_price\lib\site-packages (from imbalanced-learn) (1.17.1)
Requirement already satisfied: scikit-learn<2,>=1.4.2 in e:\data science\projects\laptop\laptop_price\lib\site-packages (from imbalanced-learn) (1.8.0)
Collecting sklearn-compat<0.2,>=0.1.5 (from imbalanced-learn)
  Using cached sklearn_compat-0.1.5-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: joblib<2,>=1.2.0 in e:\data science\projects\laptop\laptop_price\lib\site-packages (from imbalanced-learn) (1.5.3)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in e:\data science\projects\laptop\laptop_price\lib\site-packages (from imbalanced-learn) (3.6.0)
Using cached imbalanced_learn-0.14.1-py3-none-any.whl (235 kB)
Using cached sklearn_compat-0.1.5-py3-none-any.whl (20 kB)
Installing collected packages: sklearn-compat, imbalanced-learn

   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   ---------------------------------------- 2/2 [imbalanced-learn]

Successfully installed imbalanced-learn-0.14.1 sklearn-compat-0.1.5

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [143]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
sm=SMOTE(random_state=42)

In [144]:
pred=sv.predict(x_test)
pred

array([64027.41754686, 64085.05743949, 63998.33559126, 64114.01305765,
       64114.02910273, 64114.26569309, 64027.53259715, 64086.93241298,
       64084.86724603, 64053.53146741, 64065.63243916, 63981.01971171,
       64087.00114738, 64114.31076385, 64086.30978216, 64013.78436465,
       64086.94252306, 64085.9170897 , 64086.92515155, 64114.19661692,
       63979.99503443, 64065.65985288, 64086.66178662, 64064.08385577,
       64017.84013555, 64065.70379765, 64077.40390615, 64114.27311195,
       64064.95483217, 64065.67374581, 63997.85165546, 64085.90129439,
       63989.84925833, 64086.99123493, 64087.01157998, 64064.75187691,
       64084.2553053 , 64086.79162474, 64063.12347952, 64086.73966814,
       64045.78690227, 64067.87226781, 64086.08867922, 63985.70533281,
       64086.1446604 , 64065.66577343, 64114.07428333, 64087.33579111,
       64101.08960327, 63998.67594469, 64087.18516753, 64013.96503722,
       64013.94652279, 64087.037745  , 64080.97227326, 64114.36750191,
       64108.76183003, 64055.66130582, 64087.01275624, 64114.23527589,
       64012.07701797, 64014.22176792, 64021.64788729, 64021.38941648,
       64086.78625261, 64085.14144174, 64113.93264446, 64020.87120929,
       64013.89957276, 63985.19689174, 64114.24249789, 64108.91804849,
       64013.37729818, 64114.31076385, 64064.89316973, 64056.52025421,
       64086.24147208, 64087.35721105, 64052.19542885, 64086.01140356,
       64065.74171538, 63985.62334948, 63993.57462199, 64065.63243916,
       64064.60332785, 63998.21542506, 64087.18176645, 64087.08706467,
       64086.15704671, 64114.11536866, 64086.68585519, 64086.99128058,
       64087.00905589, 64082.91911517, 64087.31162424, 64086.9749925 ,
       64112.22440737, 64087.00114738, 64066.03841686, 64083.9049554 ,
       64020.825641  , 64065.65312531, 64087.28204801, 64075.6028637 ,
       64087.26863235, 64083.2967749 , 64086.54086743, 63998.01368299,
       64065.60843188, 64086.37731774, 64086.29985367, 64114.3486306 ,
       64080.70884375, 64083.14555492, 63985.53501091, 63998.36007806,
       64037.63945888, 64007.42940286, 64053.072152  , 64086.91274714,
       64114.28091061, 64086.83567668, 64076.66679832, 63998.36258884,
       64087.02169427, 64087.30412995, 64011.50688261, 64086.73603213,
       64114.2056717 , 64065.3866286 , 64031.02207135, 64086.54926825,
       64086.77702695, 64114.33841998, 64065.67724134, 63998.40153466,
       64114.28295441, 64086.49002359, 64087.11118136, 63998.40891642,
       64112.05095246, 63985.12013515, 64021.07365684, 63996.66308402,
       64086.29371848, 64114.26231623, 63986.0101004 , 63994.06457174,
       64078.95864673, 64080.78731821, 64085.3273365 , 64114.10003961,
       64014.46985556, 63985.78734294, 64087.09686666, 64114.34036514,
       64087.00905589, 64086.96117477, 63997.56686365, 64087.32359032,
       64087.16683429])

In [145]:
pred[0:20]

array([64027.41754686, 64085.05743949, 63998.33559126, 64114.01305765,
       64114.02910273, 64114.26569309, 64027.53259715, 64086.93241298,
       64084.86724603, 64053.53146741, 64065.63243916, 63981.01971171,
       64087.00114738, 64114.31076385, 64086.30978216, 64013.78436465,
       64086.94252306, 64085.9170897 , 64086.92515155, 64114.19661692])

In [146]:
y_test[0:20]

      Price
196   50990
299   72990
171   41490
537  144690
551  129990
809  142990
610  104990
328   64990
222   51990
415  125394
68    41990
658   32917
239   65990
819  144990
758   57999
433  291190
316  106490
111   45490
280   61290
544  154990

In [147]:
from sklearn.tree import DecisionTreeRegressor,DecisionTreeClassifier

In [148]:
dtr=DecisionTreeRegressor()
dtr.get_params()

{'ccp_alpha': 0.0,
 'criterion': 'squared_error',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'random_state': None,
 'splitter': 'best'}

In [149]:
dtr.fit(x_train, y_train)

DecisionTreeRegressor()

In [150]:
dtr.score(x_test, y_test)

0.5835387699333676

In [151]:
dtr.score(x_train, y_train)

0.9937783949307265

In [152]:
from sklearn.tree import DecisionTreeRegressor
import joblib
dtr = DecisionTreeRegressor()
dtr.fit(x_train, y_train )

DecisionTreeRegressor()

In [ ]:
from sklearn.tree import DecisionTreeRegressor
import joblib
dtr = DecisionTreeRegressor()
dtr.fit(x_train, y_train )

['laptop_model_joblib']

In [154]:
model=joblib.load('laptop_model_joblib')

In [155]:
dtr.predict(x_test)

array([119990.        , 105990.        ,  39490.        , 179990.        ,
       192990.        , 234990.        , 102990.        , 106990.        ,
        53990.        , 155411.        ,  39990.        ,  39990.        ,
        58990.        , 139741.66666667,  68500.        , 109590.        ,
        86999.        ,  41990.        ,  76300.        , 192990.        ,
        43000.        ,  36490.        ,  61990.        ,  32490.        ,
        39490.        ,  56490.        ,  49970.        , 234990.        ,
        73990.        ,  36999.        ,  61990.        ,  68990.        ,
        44490.        ,  89998.        ,  77990.        ,  36990.        ,
       169990.        ,  70990.        ,  38990.        ,  66999.        ,
        38990.        ,  47990.        ,  49990.        ,  38680.        ,
       128990.        ,  48990.        , 179990.        ,  78990.        ,
        84500.        , 104990.        , 239759.        , 139990.        ,
       139990.        ,  59990.        ,  73990.        ,  72990.        ,
        84500.        ,  43970.        , 147000.        , 139990.        ,
        60990.        ,  24990.        ,  40990.        ,  57990.        ,
        49990.        ,  55990.        , 192990.        ,  45990.        ,
        40990.        ,  38680.        ,  85990.        , 114990.        ,
       179990.        , 139741.66666667,  37890.        ,  39990.        ,
       184990.        ,  79990.        ,  66990.        ,  58990.        ,
        48990.        ,  56990.        ,  54490.        ,  39990.        ,
        38990.        ,  54990.        ,  88488.        ,  92000.        ,
        65990.        , 139741.66666667,  87990.        ,  57500.        ,
        79990.        ,  56990.        ,  34990.        ,  99990.        ,
       179990.        ,  58990.        ,  36000.        ,  73990.        ,
        39490.        ,  39999.        ,  79990.        ,  48990.        ,
        34990.        ,  63990.        ,  45930.        , 112990.        ,
        39998.        ,  84990.        ,  61990.        , 130990.        ,
        73990.        ,  52990.        ,  48790.        ,  48790.        ,
        35990.        ,  62990.        ,  58990.        ,  41990.        ,
        99990.        ,  55490.        ,  66990.        ,  70090.        ,
       109999.        ,  84988.        ,  35990.        ,  49990.        ,
       165990.        ,  36990.        ,  55490.        ,  59999.        ,
        79990.        , 134656.66666667,  56490.        ,  49990.        ,
       105495.        ,  85990.        ,  60240.        ,  64990.        ,
        72990.        ,  39490.        ,  57990.        , 112990.        ,
        61990.        , 157499.5       ,  58540.        ,  52990.        ,
        45990.        ,  49970.        ,  71090.        , 139741.66666667,
        58990.        ,  41490.        ,  64990.        , 134656.66666667,
        79990.        ,  79990.        ,  61990.        ,  78990.        ,
        88488.        ])

In [156]:
y_test

      Price
196   50990
299   72990
171   41490
537  144690
551  129990
..      ...
368  114990
361  126000
446   57990
767  106990
529  110999

[161 rows x 1 columns]